version: '3.9'

services:
  api:
    build:
      context: ./apps/api
      dockerfile: ../../docker/api.Dockerfile
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./apps/api:/app
    ports:
      - "8000:8000"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: keirin
      POSTGRES_PASSWORD: keirin
      POSTGRES_DB: keirin
    ports:
      - "5432:5432"
